"""Initial Migration

Revision ID: 02df1c186ee2
Revises: 64456b820828
Create Date: 2021-09-15 12:39:12.157935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02df1c186ee2'
down_revision = '64456b820828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
