"""Initial Migration

Revision ID: 64456b820828
Revises: 71acd34fa535
Create Date: 2021-09-15 12:38:08.572706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64456b820828'
down_revision = '71acd34fa535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
