"""Initial Migration

Revision ID: 71acd34fa535
Revises: b1c2d3960a6e
Create Date: 2021-09-15 12:33:37.631030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71acd34fa535'
down_revision = 'b1c2d3960a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
